### ISSUE TITLE
Mod no longer works properly in 1.19.

### ISSUE THREAD

**Issue by Kichura** [haykam821/Sneaky-Screens#1]
Due to mojang changing up class IDs again, booting this mod up in 1.19 will now result in this [error log](https://pastebin.com/raw/0SAQz71P).

**Comment by Kichura** [comment]
Closing this issue as Fourmisain's 1.19 fork has resolved my problem.

**Comment by haykam821** [comment]
[Version 1.0.2](https://github.com/haykam821/Sneaky-Screens/releases/tag/1.0.2) supports Minecraft 1.19.
